FROM python:3.11-alpine

# Add required apk packages
RUN apk add --no-cache \
	cairo-dev \
	dbus-dev \
	doxygen \
	gcc \
	git \
	gobject-introspection-dev \
	libc-dev \
	make \
	openssh-client \
	pkgconf \
	python3 \
	py3-pip

# Install pip packages
COPY requirements.txt /tmp/requirements.txt
RUN python3 -m pip install -r /tmp/requirements.txt
