FROM python:3.11-alpine

# Add required apk packages
RUN apk add --no-cache \
	cairo-dev \
	dbus-dev \
	doxygen \
	gcc \
	git \
	gobject-introspection-dev \
	libc-dev \
	make \
	openssh-client \
	pkgconf \
	python3 \
	py3-pip

# Install pip packages
RUN python3 -m pip install \
	# Primary mkdocs package
	# mkdocs needs to be pegged to 1.4.3 until `mkdocs_puml` is updated.
	#   Attempting to use mkdocs 1.5 results in the following error:
	# ```
	# File "/usr/local/lib/python3.11/site-packages/mkdocs_puml/plugin.py", line 6, in <module>
	#     from mkdocs.plugins import BasePlugin, Page
	# ImportError: cannot import name 'Page' from 'mkdocs.plugins' (/usr/local/lib/python3.11/site-packages/mkdocs/plugins.py)
	# ```
	mkdocs==1.4.3 \
	# Packages used to enable the material mkdocs theme
	mkdocs-material \
	mkdocs-git-revision-date-localized-plugin \
	pygments \
	# Packages for documentation generation
	mkdocs-awesome-pages-plugin \
	doxypypy \
	mkdocs_puml

# Temporarily dump the python packages being used so that they can be saved
#   in the repository
RUN python3 -m pip freeze
