nav:
  - Propositional Logic: propositional-logic.md
  - Logical Equivalences: logical-equivalences.md
  - Boolean Algebra: boolean-algebra.md
  - "Appendix 1: Proofs for Logical Equivalences": appendix-1.md
  - "Appendix 2: Truth Tables for Logical Equivalences": appendix-2.md
