name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      force_publish:
        description: Whether to publish docs regardless of whether any changes were made.
        required: false
        default: "false"

permissions:
  contents: write

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start docker containers
        env:
          FORCE_PUBLISH: ${{ inputs.force_publish }}
          PUBLISH_SSH_KEY: ${{ secrets.PUBLISH_SSH_KEY }}
        working-directory: docker/mkdocs
        run: docker compose up -d

      - name: Build and publish docs
        # The container name listed here must match the name in the
        #   `docker-compose.yml` file for the container that will run
        #   the mkdocs commands
        run: >
          docker exec publish_docs ash -c
          "cd /home/wizard/docker/mkdocs && ./publish.sh"

      - name: Stop docker containers
        working-directory: docker/mkdocs
        run: docker compose down
